package com.zdatai.finverus.enums;

public enum ClientSectionInfoEnum {
    IDENTITY_DETAILS,
    PERSONAL_INFORMATION,
    CITIZENSHIP_INFORMATION,
    CONTACT,
    ADDRESS,
    SOCIAL_MEDIA,
    PROFESSIONAL_AND_TAX_DETAIL,
    SPOUSE_AND_CHILDREN,
    INCOME_AND_WEALTH_DECLARATION,
    EMPLOYEE_FIRST_SECTION,
    EMPLOYEE_SECOND_SECTION,
    OTHER
}
