databaseChangeLog:
  - changeSet:
      id: create-product-sub-scheme-table
      author: umesh
      changes:
        - createTable:
            tableName: produt_sub_scheme
            columns:
              - column:
                  name: scheme_id
                  type: bigint
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: scheme_name
                  type: varchar(50)
                  constraints:
                    nullable: true

              - column:
                  name: effective_date
                  type: date
                  constraints:
                    nullable: true

              - column:
                  name: expire_date
                  type: date
                  constraints:
                    nullable: true

              - column:
                  name: schema_status
                  type: varchar(255)
                  constraints:
                    nullable: true

              # Columns from AuditCreateUser
              - column:
                  name: created_user
                  type: varchar(50)
                  constraints:
                    nullable: false

              - column:
                  name: created_date_time
                  type: datetime
                  constraints:
                    nullable: false

              # Columns from AuditModifyUser
              - column:
                  name: modified_user
                  type: varchar(50)
                  constraints:
                    nullable: false

              - column:
                  name: modified_date_time
                  type: datetime
                  constraints:
                    nullable: false

              - column:
                  name: status
                  type: varchar(50)
                  constraints:
                    nullable: true

              # Version column from BaseEntity
              - column:
                  name: version
                  type: int
                  defaultValue: 0
                  constraints:
                    nullable: false